---
- name: Create ELK Stack
  hosts: 127.0.0.1
  become: yes
  become_method: sudo
  connection: local

  tasks:

  - name: Add Docker GPG key.
    rpm_key:
      key: https://download.docker.com/linux/centos/gpg
      state: present

  - name: Add Docker repository.
    get_url:
      url: "https://download.docker.com/linux/centos/docker-ce.repo"
      dest: '/etc/yum.repos.d/docker-ce.repo'
      owner: root
      group: root
      mode: 0644

  - name: Add Elasticsearch GPG key.
    rpm_key:
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Add Elasticsearch repository.
    template:
      src: ./files/elastic/elasticsearch.repo.j2
      dest: /etc/yum.repos.d/elasticsearch.repo
      mode: 0644

  - name: Install Docker.
    package:
      name: docker-ce
      state: latest

  - name: Install rsync to syncronize files
    package:
      name: rsync
      state: latest

  - name: Ensure Docker is started and enabled at boot.
    service:
      name: docker
      state: started
      enabled: true

  - name: Ensure EPEL is enabled 
    yum: 
      name: epel-release 
      state: present 

  - name: install python-pip
    yum:
      name: python-pip
      state: latest

  - name: pip docker
    pip:
      name: docker

  - name: pip docker-compose
    pip:
      name: docker-compose

  - name: update sysctl
    sysctl:
      name: vm.max_map_count
      value: 262144
      state: present
      reload: yes

  - name: Elasticsearch docker image
    docker_image:
      name: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
      source: pull

  - name: Kibana docker image
    docker_image:
      name: docker.elastic.co/kibana/kibana:7.0.0
      source: pull

  - name: Logstash docker image
    docker_image:
      name: docker.elastic.co/logstash/logstash:7.0.0
      source: pull

  - name: Copy files to /opt/elk-siem
    copy:
      src: files/
      dest: /opt/elk-siem

  - name: Create desktop shortcut image
    copy:
      src: images/
      dest: /usr/share/icons/

  - name: Create Fleet desktop shortcut
    copy:
      dest: /home/guerilla/Desktop/Kibana.desktop
      content: |
        [Desktop Entry]
        Encoding=UTF-8
        Name=Kibana
        Type=Link
        URL=http://127.0.0.1:5601
        Icon=/usr/share/icons/kibana.png
        Name[en_US]=Kibana

  - name: docker-compose up
    docker_compose:
      project_src: /opt/elk-siem
      state: present
